version: "3"
services:

  nginx:
    depends_on:
      - apiserver
      - webclient
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx

  apiserver:
    build:
      context: ./apiserver
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./apiserver:/app
    ports:
      - 3001:3001

  webclient:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./webclient
    volumes:
      - /app/node_modules
      - ./webclient:/app
    ports:
      - 3000:3000
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    
    
      