version: "3"
services:

  nginx:
    depends_on:
      - apiserver
      - webclient
    restart: always
    image: "pprieto009/betterreads-nginx"
    ports:
      - 80:80

  apiserver:
    image: "pprieto009/betterreads-apiserver"
    mem_limit: 128m
    hostname: apiserver
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
    restart: always

  webclient:
    stdin_open: true
    image: "pprieto009/betterreads-webclient"
    mem_limit: 128m
    hostname: webclient
    restart: always
    environment:
      - MONGO_DB_URL=$MONGO_DB_URL
