name: Deploy BetterReads
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
 
      - run: docker build -t pprieto009/betterreads-webclient ./webclient
      - run: docker build -t pprieto009/betterreads-nginx ./nginx
      - run: docker build -t pprieto009/betterreads-apiserver ./apiserver
 
      - run: docker push pprieto009/betterreads-webclient
      - run: docker push pprieto009/betterreads-nginx
      - run: docker push pprieto009/betterreads-apiserver
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: betterreads
          environment_name: Betterreads-env
          existing_bucket_name: elasticbeanstalk-us-east-2-381492186207
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
